#!/bin/sh

echo
echo "-----Normalizing Regular UFO..."
psfnormalize -p checkfix=fix source/BeriaNew-Regular.ufo

echo
echo "-----Updating woff metadata file..."
psfmakewoffmetadata -q -n "BeriaNew" -i "org.sil.fonts" source/BeriaNew-Regular.ufo

echo
echo "-----Preflight completed!"
