#!/bin/sh

echo "-----Updating UFOs from Glyphs file..."
psfglyphs2ufo source/BeriaNew-Regular.glyphs source

echo "-----Normalizing Regular UFO..."
psfnormalize -p checkfix=fix source/BeriaNew-Regular.ufo

echo "-----Preflight completed!"
